### PR TITLE
API object added to __init__.py

### PR DESCRIPTION
**Pull request by Aykhan-s**

### CODE REVIEW

**Comment by thicccat688** [comment]
Hi Aykhan,

Thanks for catching this mistake!

I saw that you closed the PR, though, is something wrong?

I'll update the package on PyPi with the fix soon.

**Comment by Aykhan-s** [comment]
> 

Hi thicccat688, 

I looked at alexreg's PR and saw that you changed the API to RecaptchaSolver. So I thought the problem was with the API naming in the README file, not the init file.

**Comment by thicccat688** [comment]
@Aykhan-s 

I changed it to RecaptchaSolver but kept the API alias for backward compatibility. I should have included it in the __init__ file, but I didn't.

I've updated the documentation to reflect the new RecaptchaSolver class and incorporated your changes (I credited you for them in the latest release). 

Thanks again for spotting this!

**Comment by Aykhan-s** [comment]
> @Aykhan-s
> 
> I changed it to RecaptchaSolver but kept the API alias for backward compatibility. I should have included it in the **init** file, but I didn't.
> 
> I've updated the documentation to reflect the new RecaptchaSolver class and incorporated your changes (I credited you for them in the latest release).
> 
> Thanks again for spotting this!

Thanks for the credit.

You're welcome.

**Pull request closed without merging**
